app = "sesame-log-shipper"
primary_region = "lhr"

[build]
  image = "ghcr.io/superfly/fly-log-shipper:latest"


[metrics]
  port = 9598
  path = "/metrics"


[[services]]
  http_checks = []
  internal_port = 8686

[env]
  SUBJECT = "logs.sesame.>"
