# fly.toml app configuration file generated for sesame-log-shipper on 2023-08-10T11:24:23+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sesame-log-shipper"
primary_region = "lhr"

[build]
  image = "ghcr.io/superfly/fly-log-shipper:latest"

[env]
  SUBJECT = "logs.sesame.>"

[[services]]
  protocol = ""
  internal_port = 8686

[metrics]
  port = 9598
  path = "/metrics"
